<?php


/**
 * ClassifierRecommendationRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * ClassifierRecommendationRequest Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ClassifierRecommendationRequest implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    static $swaggerModelName = 'ClassifierRecommendationRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'text' => 'string',
        'count' => 'int',
        'use_emphasizing' => 'bool',
        'need_tag_in_result' => 'bool'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'text' => 'Text',
        'count' => 'Count',
        'use_emphasizing' => 'UseEmphasizing',
        'need_tag_in_result' => 'NeedTagInResult'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'text' => 'setText',
        'count' => 'setCount',
        'use_emphasizing' => 'setUseEmphasizing',
        'need_tag_in_result' => 'setNeedTagInResult'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'text' => 'getText',
        'count' => 'getCount',
        'use_emphasizing' => 'getUseEmphasizing',
        'need_tag_in_result' => 'getNeedTagInResult'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $text The text the you want to classify
      * @var string
      */
    protected $text;
    
    /**
      * $count How many results you want to see in the response (default value is 3)
      * @var int
      */
    protected $count;
    
    /**
      * $use_emphasizing Use emphasizing algorithm during this recommendation
      * @var bool
      */
    protected $use_emphasizing;
    
    /**
      * $need_tag_in_result If you want to see all the tag object in the response
      * @var bool
      */
    protected $need_tag_in_result;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        

        if ($data != null) {
            $this->text = $data["text"];
            $this->count = $data["count"];
            $this->use_emphasizing = $data["use_emphasizing"];
            $this->need_tag_in_result = $data["need_tag_in_result"];
        }
    }
    
    /**
     * Gets text
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }
  
    /**
     * Sets text
     * @param string $text The text the you want to classify
     * @return $this
     */
    public function setText($text)
    {
        
        $this->text = $text;
        return $this;
    }
    
    /**
     * Gets count
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }
  
    /**
     * Sets count
     * @param int $count How many results you want to see in the response (default value is 3)
     * @return $this
     */
    public function setCount($count)
    {
        
        $this->count = $count;
        return $this;
    }
    
    /**
     * Gets use_emphasizing
     * @return bool
     */
    public function getUseEmphasizing()
    {
        return $this->use_emphasizing;
    }
  
    /**
     * Sets use_emphasizing
     * @param bool $use_emphasizing Use emphasizing algorithm during this recommendation
     * @return $this
     */
    public function setUseEmphasizing($use_emphasizing)
    {
        
        $this->use_emphasizing = $use_emphasizing;
        return $this;
    }
    
    /**
     * Gets need_tag_in_result
     * @return bool
     */
    public function getNeedTagInResult()
    {
        return $this->need_tag_in_result;
    }
  
    /**
     * Sets need_tag_in_result
     * @param bool $need_tag_in_result If you want to see all the tag object in the response
     * @return $this
     */
    public function setNeedTagInResult($need_tag_in_result)
    {
        
        $this->need_tag_in_result = $need_tag_in_result;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


