<?php


/**
 * ClassifierRecommendationResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * ClassifierRecommendationResult Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ClassifierRecommendationResult implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    static $swaggerModelName = 'ClassifierRecommendationResult';

    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'tag_id' => 'string',
        'score' => 'double',
        'tag' => '\Swagger\Client\Model\Tag',
        'is_emphasized' => 'bool'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'tag_id' => 'TagId',
        'score' => 'Score',
        'tag' => 'Tag',
        'is_emphasized' => 'IsEmphasized'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'tag_id' => 'setTagId',
        'score' => 'setScore',
        'tag' => 'setTag',
        'is_emphasized' => 'setIsEmphasized'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'tag_id' => 'getTagId',
        'score' => 'getScore',
        'tag' => 'getTag',
        'is_emphasized' => 'getIsEmphasized'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $tag_id The recommended tag id
      * @var string
      */
    protected $tag_id;
    
    /**
      * $score The score that belongs to the tag id
      * @var double
      */
    protected $score;
    
    /**
      * $tag 
      * @var \Swagger\Client\Model\Tag
      */
    protected $tag;
    
    /**
      * $is_emphasized If there was applied emphasizing by this tag
      * @var bool
      */
    protected $is_emphasized;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        

        if ($data != null) {
            $this->tag_id = $data["tag_id"];
            $this->score = $data["score"];
            $this->tag = $data["tag"];
            $this->is_emphasized = $data["is_emphasized"];
        }
    }
    
    /**
     * Gets tag_id
     * @return string
     */
    public function getTagId()
    {
        return $this->tag_id;
    }
  
    /**
     * Sets tag_id
     * @param string $tag_id The recommended tag id
     * @return $this
     */
    public function setTagId($tag_id)
    {
        
        $this->tag_id = $tag_id;
        return $this;
    }
    
    /**
     * Gets score
     * @return double
     */
    public function getScore()
    {
        return $this->score;
    }
  
    /**
     * Sets score
     * @param double $score The score that belongs to the tag id
     * @return $this
     */
    public function setScore($score)
    {
        
        $this->score = $score;
        return $this;
    }
    
    /**
     * Gets tag
     * @return \Swagger\Client\Model\Tag
     */
    public function getTag()
    {
        return $this->tag;
    }
  
    /**
     * Sets tag
     * @param \Swagger\Client\Model\Tag $tag 
     * @return $this
     */
    public function setTag($tag)
    {
        
        $this->tag = $tag;
        return $this;
    }
    
    /**
     * Gets is_emphasized
     * @return bool
     */
    public function getIsEmphasized()
    {
        return $this->is_emphasized;
    }
  
    /**
     * Sets is_emphasized
     * @param bool $is_emphasized If there was applied emphasizing by this tag
     * @return $this
     */
    public function setIsEmphasized($is_emphasized)
    {
        
        $this->is_emphasized = $is_emphasized;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


