<?php


/**
 * CompressSettings
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * CompressSettings Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CompressSettings implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    static $swaggerModelName = 'CompressSettings';

    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'category_occurence' => 'int',
        'data_set_occurence' => 'int',
        'operator' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'category_occurence' => 'CategoryOccurence',
        'data_set_occurence' => 'DataSetOccurence',
        'operator' => 'Operator'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'category_occurence' => 'setCategoryOccurence',
        'data_set_occurence' => 'setDataSetOccurence',
        'operator' => 'setOperator'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'category_occurence' => 'getCategoryOccurence',
        'data_set_occurence' => 'getDataSetOccurence',
        'operator' => 'getOperator'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $category_occurence 
      * @var int
      */
    protected $category_occurence;
    
    /**
      * $data_set_occurence 
      * @var int
      */
    protected $data_set_occurence;
    
    /**
      * $operator 
      * @var string
      */
    protected $operator;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        

        if ($data != null) {
            $this->category_occurence = $data["category_occurence"];
            $this->data_set_occurence = $data["data_set_occurence"];
            $this->operator = $data["operator"];
        }
    }
    
    /**
     * Gets category_occurence
     * @return int
     */
    public function getCategoryOccurence()
    {
        return $this->category_occurence;
    }
  
    /**
     * Sets category_occurence
     * @param int $category_occurence 
     * @return $this
     */
    public function setCategoryOccurence($category_occurence)
    {
        
        $this->category_occurence = $category_occurence;
        return $this;
    }
    
    /**
     * Gets data_set_occurence
     * @return int
     */
    public function getDataSetOccurence()
    {
        return $this->data_set_occurence;
    }
  
    /**
     * Sets data_set_occurence
     * @param int $data_set_occurence 
     * @return $this
     */
    public function setDataSetOccurence($data_set_occurence)
    {
        
        $this->data_set_occurence = $data_set_occurence;
        return $this;
    }
    
    /**
     * Gets operator
     * @return string
     */
    public function getOperator()
    {
        return $this->operator;
    }
  
    /**
     * Sets operator
     * @param string $operator 
     * @return $this
     */
    public function setOperator($operator)
    {
        $allowed_values = array("AND", "OR");
        if (!in_array($operator, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'operator', must be one of 'AND', 'OR'");
        }
        $this->operator = $operator;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


