<?php


/**
 * DocumentSampleSettings
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * DocumentSampleSettings Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocumentSampleSettings implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    static $swaggerModelName = 'DocumentSampleSettings';

    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'id' => 'string',
        'tag_ids' => 'string[]',
        'is_stratified' => 'bool',
        'pagination' => '\Swagger\Client\Model\Pagination',
        'percent' => 'double',
        'size' => 'int',
        'ids_only' => 'bool'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'id' => 'Id',
        'tag_ids' => 'TagIds',
        'is_stratified' => 'IsStratified',
        'pagination' => 'Pagination',
        'percent' => 'Percent',
        'size' => 'Size',
        'ids_only' => 'IdsOnly'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'id' => 'setId',
        'tag_ids' => 'setTagIds',
        'is_stratified' => 'setIsStratified',
        'pagination' => 'setPagination',
        'percent' => 'setPercent',
        'size' => 'setSize',
        'ids_only' => 'setIdsOnly'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'id' => 'getId',
        'tag_ids' => 'getTagIds',
        'is_stratified' => 'getIsStratified',
        'pagination' => 'getPagination',
        'percent' => 'getPercent',
        'size' => 'getSize',
        'ids_only' => 'getIdsOnly'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $id 
      * @var string
      */
    protected $id;
    
    /**
      * $tag_ids 
      * @var string[]
      */
    protected $tag_ids;
    
    /**
      * $is_stratified 
      * @var bool
      */
    protected $is_stratified;
    
    /**
      * $pagination 
      * @var \Swagger\Client\Model\Pagination
      */
    protected $pagination;
    
    /**
      * $percent 
      * @var double
      */
    protected $percent;
    
    /**
      * $size 
      * @var int
      */
    protected $size;
    
    /**
      * $ids_only 
      * @var bool
      */
    protected $ids_only;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        

        if ($data != null) {
            $this->id = $data["id"];
            $this->tag_ids = $data["tag_ids"];
            $this->is_stratified = $data["is_stratified"];
            $this->pagination = $data["pagination"];
            $this->percent = $data["percent"];
            $this->size = $data["size"];
            $this->ids_only = $data["ids_only"];
        }
    }
    
    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }
  
    /**
     * Sets id
     * @param string $id 
     * @return $this
     */
    public function setId($id)
    {
        
        $this->id = $id;
        return $this;
    }
    
    /**
     * Gets tag_ids
     * @return string[]
     */
    public function getTagIds()
    {
        return $this->tag_ids;
    }
  
    /**
     * Sets tag_ids
     * @param string[] $tag_ids 
     * @return $this
     */
    public function setTagIds($tag_ids)
    {
        
        $this->tag_ids = $tag_ids;
        return $this;
    }
    
    /**
     * Gets is_stratified
     * @return bool
     */
    public function getIsStratified()
    {
        return $this->is_stratified;
    }
  
    /**
     * Sets is_stratified
     * @param bool $is_stratified 
     * @return $this
     */
    public function setIsStratified($is_stratified)
    {
        
        $this->is_stratified = $is_stratified;
        return $this;
    }
    
    /**
     * Gets pagination
     * @return \Swagger\Client\Model\Pagination
     */
    public function getPagination()
    {
        return $this->pagination;
    }
  
    /**
     * Sets pagination
     * @param \Swagger\Client\Model\Pagination $pagination 
     * @return $this
     */
    public function setPagination($pagination)
    {
        
        $this->pagination = $pagination;
        return $this;
    }
    
    /**
     * Gets percent
     * @return double
     */
    public function getPercent()
    {
        return $this->percent;
    }
  
    /**
     * Sets percent
     * @param double $percent 
     * @return $this
     */
    public function setPercent($percent)
    {
        
        $this->percent = $percent;
        return $this;
    }
    
    /**
     * Gets size
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }
  
    /**
     * Sets size
     * @param int $size 
     * @return $this
     */
    public function setSize($size)
    {
        
        $this->size = $size;
        return $this;
    }
    
    /**
     * Gets ids_only
     * @return bool
     */
    public function getIdsOnly()
    {
        return $this->ids_only;
    }
  
    /**
     * Sets ids_only
     * @param bool $ids_only 
     * @return $this
     */
    public function setIdsOnly($ids_only)
    {
        
        $this->ids_only = $ids_only;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


