<?php


/**
 * SearchResultWrapper
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * SearchResultWrapper Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SearchResultWrapper implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    static $swaggerModelName = 'SearchResultWrapper';

    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'auto_complete_result_list' => '\Swagger\Client\Model\AutoCompleteResult[]',
        'classifier_result_list' => '\Swagger\Client\Model\SearchClassifierRecommendationResult[]',
        'search_result_list' => '\Swagger\Client\Model\SearchResult[]',
        'total' => 'int'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'auto_complete_result_list' => 'AutoCompleteResultList',
        'classifier_result_list' => 'ClassifierResultList',
        'search_result_list' => 'SearchResultList',
        'total' => 'Total'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'auto_complete_result_list' => 'setAutoCompleteResultList',
        'classifier_result_list' => 'setClassifierResultList',
        'search_result_list' => 'setSearchResultList',
        'total' => 'setTotal'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'auto_complete_result_list' => 'getAutoCompleteResultList',
        'classifier_result_list' => 'getClassifierResultList',
        'search_result_list' => 'getSearchResultList',
        'total' => 'getTotal'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $auto_complete_result_list List of the AutoComplete suggestions
      * @var \Swagger\Client\Model\AutoCompleteResult[]
      */
    protected $auto_complete_result_list;
    
    /**
      * $classifier_result_list List of the Classifier results of the input text
      * @var \Swagger\Client\Model\SearchClassifierRecommendationResult[]
      */
    protected $classifier_result_list;
    
    /**
      * $search_result_list The matched documents with relevance scores
      * @var \Swagger\Client\Model\SearchResult[]
      */
    protected $search_result_list;
    
    /**
      * $total The total matched document count
      * @var int
      */
    protected $total;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        

        if ($data != null) {
            $this->auto_complete_result_list = $data["auto_complete_result_list"];
            $this->classifier_result_list = $data["classifier_result_list"];
            $this->search_result_list = $data["search_result_list"];
            $this->total = $data["total"];
        }
    }
    
    /**
     * Gets auto_complete_result_list
     * @return \Swagger\Client\Model\AutoCompleteResult[]
     */
    public function getAutoCompleteResultList()
    {
        return $this->auto_complete_result_list;
    }
  
    /**
     * Sets auto_complete_result_list
     * @param \Swagger\Client\Model\AutoCompleteResult[] $auto_complete_result_list List of the AutoComplete suggestions
     * @return $this
     */
    public function setAutoCompleteResultList($auto_complete_result_list)
    {
        
        $this->auto_complete_result_list = $auto_complete_result_list;
        return $this;
    }
    
    /**
     * Gets classifier_result_list
     * @return \Swagger\Client\Model\SearchClassifierRecommendationResult[]
     */
    public function getClassifierResultList()
    {
        return $this->classifier_result_list;
    }
  
    /**
     * Sets classifier_result_list
     * @param \Swagger\Client\Model\SearchClassifierRecommendationResult[] $classifier_result_list List of the Classifier results of the input text
     * @return $this
     */
    public function setClassifierResultList($classifier_result_list)
    {
        
        $this->classifier_result_list = $classifier_result_list;
        return $this;
    }
    
    /**
     * Gets search_result_list
     * @return \Swagger\Client\Model\SearchResult[]
     */
    public function getSearchResultList()
    {
        return $this->search_result_list;
    }
  
    /**
     * Sets search_result_list
     * @param \Swagger\Client\Model\SearchResult[] $search_result_list The matched documents with relevance scores
     * @return $this
     */
    public function setSearchResultList($search_result_list)
    {
        
        $this->search_result_list = $search_result_list;
        return $this;
    }
    
    /**
     * Gets total
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }
  
    /**
     * Sets total
     * @param int $total The total matched document count
     * @return $this
     */
    public function setTotal($total)
    {
        
        $this->total = $total;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


