<?php
/**
 * DocumentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DocumentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DocumentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for bulkDocuments
     *
     * 
     *
     */
    public function test_bulkDocuments() {

    }
    
    /**
     * Test case for copyDocuments
     *
     * 
     *
     */
    public function test_copyDocuments() {

    }
    
    /**
     * Test case for createDocument
     *
     * 
     *
     */
    public function test_createDocument() {

    }
    
    /**
     * Test case for deleteDocument
     *
     * 
     *
     */
    public function test_deleteDocument() {

    }
    
    /**
     * Test case for getDocument
     *
     * 
     *
     */
    public function test_getDocument() {

    }
    
    /**
     * Test case for getFilteredDocuments
     *
     * 
     *
     */
    public function test_getFilteredDocuments() {

    }
    
    /**
     * Test case for getSampleDocuments
     *
     * 
     *
     */
    public function test_getSampleDocuments() {

    }
    
    /**
     * Test case for moveDocuments
     *
     * 
     *
     */
    public function test_moveDocuments() {

    }
    
    /**
     * Test case for updateDocument
     *
     * 
     *
     */
    public function test_updateDocument() {

    }
    
}

