<?php
/**
 * PrcServiceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * PrcServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PrcServiceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for prcActivateService
     *
     * 
     *
     */
    public function test_prcActivateService() {

    }
    
    /**
     * Test case for prcDeactivateService
     *
     * 
     *
     */
    public function test_prcDeactivateService() {

    }
    
    /**
     * Test case for prcExportDictionaries
     *
     * 
     *
     */
    public function test_prcExportDictionaries() {

    }
    
    /**
     * Test case for prcGetService
     *
     * 
     *
     */
    public function test_prcGetService() {

    }
    
    /**
     * Test case for prcIndexPartialService
     *
     * 
     *
     */
    public function test_prcIndexPartialService() {

    }
    
    /**
     * Test case for prcIndexService
     *
     * 
     *
     */
    public function test_prcIndexService() {

    }
    
    /**
     * Test case for prcKeywordsService
     *
     * 
     *
     */
    public function test_prcKeywordsService() {

    }
    
    /**
     * Test case for prcPrepareService
     *
     * 
     *
     */
    public function test_prcPrepareService() {

    }
    
    /**
     * Test case for prcRecommendByIdService
     *
     * 
     *
     */
    public function test_prcRecommendByIdService() {

    }
    
    /**
     * Test case for prcRecommendService
     *
     * 
     *
     */
    public function test_prcRecommendService() {

    }
    
}

